AWSTemplateFormatVersion: '2010-09-09'
Description: 'The security groups get their own stack so they can refer to each other.'
Parameters:
  VPCId:
    Description: The vpc to add the security groups to.
    Type: AWS::EC2::VPC::Id
Resources:
  containersecgroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic from load balancer
      VpcId: !Ref 'VPCId'
      SecurityGroupIngress:
        - IpProtocol: -1
          SourceSecurityGroupId: !Ref 'publiclbsecgroup'
  dbsecgroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Ingress for DB
      VpcId: !Ref 'VPCId'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          SourceSecurityGroupId: !Ref 'containersecgroup'
  publiclbsecgroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow all traffic to load balancer
      VpcId: !Ref 'VPCId'
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: '0.0.0.0/0'
Outputs:
  LbGroup:
    Description: The security group for load balancer access
    Value: !Ref 'publiclbsecgroup'
    Export:
      Name: !Sub '${AWS::StackName}-LB'
  DatabaseGroup:
    Description: The security group for database access
    Value: !Ref 'dbsecgroup'
    Export:
      Name: !Sub '${AWS::StackName}-DB'
  ContainerGroup:
    Description: The security group for the container itself
    Value: !Ref 'containersecgroup'
    Export:
      Name: !Sub '${AWS::StackName}-Container'
